eureka:
  client:
    registerWithEureka: false

server:
  port: 8080

logging:
  file:
    name: app.log

spring:
  main:
    web-application-type: reactive
  application:
    name: msvc-gateway

  cloud:
    gateway:
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/students/**
        - id: courses
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/courses/**
